CREATE DATABASE psbe

GO
USE psbe

GO
CREATE TABLE Projeto
(
	Id INT PRIMARY KEY IDENTITY,
	Titulo VARCHAR(30) NOT NULL,
	Situacao VARCHAR(40) NOT NULL,
	DataInicio VARCHAR(10) NOT NULL,
	Tecnologias VARCHAR(50) NOT NULL,
	Requisitos VARCHAR(50) NOT NULL
)

SELECT * FROM Projeto

GO
CREATE TABLE Usuario
(
	Id INT PRIMARY KEY IDENTITY,
	Email VARCHAR(50) UNIQUE NOT NULL,
	Senha VARCHAR(200) NOT NULL
)

SELECT * FROM Usuario